### ISSUE TITLE
Refactor stylesheets to not use the !important rule

### ISSUE THREAD

**Issue by aaryak-shah** [nafees87n/codebox#14]
Some of the styles in `Homepage.css` are utilising the `!important` rule. While this does not induce any errors, it is generally possible to write a stylesheet without using this directive. This will ensure the css is easier to debug and enhance in the future.

Refactor the css to remove the use of `!important` while ensuring the UI design is not affected. This includes keeping the responsiveness of the page intact.

**Comment by Evavic44** [comment]
I'll be working on this, kindly assign it to me. @aaryak-shah

**Comment by mounicasruthi** [comment]
I would like to work on this, can you please assign it to me? @aaryak-shah

**Comment by aaryak-shah** [comment]
@mounicasruthi sure, go ahead!
