### ISSUE TITLE
Improve the styling of the Nav bar

### ISSUE THREAD

**Issue by nafees87n** [nafees87n/codebox#16]

**Comment by aaryak-shah** [comment]
@kailash360 looking good!

Yes it should be alright to use material icons, but can you elaborate a bit on what you will use it for?

**Comment by kailash360** [comment]
I wanted to add icons on tne navbar elements. I used react-icons instead.
![image](https://user-images.githubusercontent.com/75155230/136581717-6c2c5181-95e9-47b8-9327-d979e187b7fc.png)
Any changes to be made?
