### ISSUE TITLE
Move the clear data button outside the session modal

### ISSUE THREAD

**Issue by nafees87n** [nafees87n/codebox#3]
The session modal contains `clear data` button, its better to have it outside the modal on the navbar.

**Comment by PuneetDabral** [comment]
sir can i do my contribution here i am new in git hub can you please help me to resolve this issue...so i feel motivated to words in open source ....

**Comment by aaryak-shah** [comment]
Hi @PuneetDabral, thanks for willing to contribute! Unfortunately at the moment, the repository and its issues are only open to students of IIITM for a college event and so we are unable to assign this issue to you

**Comment by PuneetDabral** [comment]
ok

**Comment by adarsharyan002** [comment]
Yeah I have tried this issue too ,plz assign this to me

**Comment by nafees87n** [comment]
@adarsharyan002 Go on!
I hope you were able to set up the local development server successfully

**Comment by nafees87n** [comment]
Thanks @adarsharyan002 for your contribution. Your PR has been merged to main
