### ISSUE TITLE
Move hardcoded variables into a separate constant provider file

### ISSUE THREAD

**Issue by nafees87n** [nafees87n/codebox#5]
Feel free to use your own judgement after looking at the code. Reach out to us for any clarification.

**Comment by kailash360** [comment]
I want to work on this issue

**Comment by nafees87n** [comment]
Sure
Go ahead @kailash360

**Comment by kailash360** [comment]
Sir, should I put regex expressions for import in the constants file?

**Comment by nafees87n** [comment]
@kailash360 
You can make two objects in the constant file you are working on `APP_CONST` and `SERVER_CONST`. The `APP_CONST` should contain frontend constants and `SERVER_CONST` all constants of the server and the executor.

Make const for different URLs like `SERVER_URL` and we can specify the entire URL there, no need to specify the port separately. Similarly, do this for the client URL and the Github links.

**Comment by nafees87n** [comment]
Make sure to test the entire application after the changes.
Check the [docs](https://github.com/nafees87n/codebox/blob/main/docs/DOCS.md) for the process to start the development server using docker. Feel free to ask if you are stuck anywhere.

@kailash360 Don't forget to pull changes from `main` as there have been some changes after you have started working.

**Comment by kailash360** [comment]
Sir, the server, client and executor cannot make an import outside their folder. So, it is difficult to keep a single file in the root directory, that can hold all the constants. I made constants file for each of the folders and it worked. Will this suffice?

**Comment by kailash360** [comment]
I have tested the project using the above method and it is working fine.

**Comment by nafees87n** [comment]
> Sir, the server, client and executor cannot make an import outside their folder. So, it is difficult to keep a single file in the root directory, that can hold all the constants. I made constants file for each of the folders and it worked. Will this suffice?

Okay. Let's keep it this way for now.
Later we could create `package.json` in the root to locally link it as an npm package in the subfolders.

**Comment by kailash360** [comment]
I have created PR #9 for this issue
