### ISSUE TITLE
Develop a theme switcher for the code editor UI

### ISSUE THREAD

**Issue by aaryak-shah** [nafees87n/codebox#7]
The code and input editors, as well as the output window utilise [Ace Editor](https://www.npmjs.com/package/react-ace), and a hard coded `Cobalt` theme is used. We want to have a system that allows us to change the editors' theme.

**Comment by kailash360** [comment]
@aaryak-shah , I want to work on this issue

**Comment by aaryak-shah** [comment]
Sure, assigning to you
